name: ML Model CI/CD Pipeline
on: [push, pull_request]

permissions:
  contents: write
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run model tests
      run: |
        # Ensure PYTHONPATH is set correctly
        export PYTHONPATH=.
        
        # Run tests with detailed output
        pytest tests/test_model.py -v
    
    - name: Train Model with Augmentations
      run: |
        export PYTHONPATH=.
        python src/train.py
    
    - name: Verify Outputs
      run: |
        # Check if models directory exists and contains a model file
        ls -l models/
        
        # Check if augmentation images were generated
        ls -l outputs/augmentations/ || echo "No augmentation images found"